### ISSUE TITLE
Add support for "." as part of a table header.

### ISSUE THREAD

**Issue by fferegrino** [xoofx/Tomlyn#12]
According to the documentation, a document like this

```toml
[servers]

  # Indentation (tabs and/or spaces) is allowed but not required
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"
```

would mean that there are three top level sections: `servers` , `servers.alpha` and `servers.beta`, however, the current Tomlyn release treats all of them as being the same `servers` section.
