### ISSUE TITLE
Invalid control character

### ISSUE THREAD

**Issue by ndtoan96** [xoofx/Tomlyn#50]
When I copy paste some string with tab character in it (not escaped) to string literal, Tomlyn throws `Unhandled exception. Tomlyn.TomlException: (117,8) : error : Invalid control character found \t`. For example:
```toml
[config]
something = 'a	b'
something_else = '''a
	b'''
```
This should be a normal use case, maybe we can have an option `strict = false` or something like that to avoid this error.
