### ISSUE TITLE
new line inserted incorrectly when saved in file

### ISSUE THREAD

**Issue by HUD-Software** [xoofx/Tomlyn#65]
Considering a simple toml like this:
```toml
[package]
authors = [ "me", "I", "myself" ]
name = "proj"
version = "0.0.1"

[profile]

```
Loading and saving it with this code cause new line to be inserted at the wrong place
```C#
TomlTable model;

using (var file = File.OpenRead("file.toml"))
{
    using StreamReader reader = new(file);
    model = Toml.ToModel(reader.ReadToEnd());
}

using (var file = File.OpenWrite("save.toml"))
{
    using StreamWriter sw = new(file);
    var str = Toml.FromModel(model);
    sw.Write(str);
}
```

Content of "save.toml" is the following:
```toml
[package]
name = "proj"
version = "0.0.1"

authors = ["me", "I", "myself"]
[profile]

```
note the new line after version and not after authors
