### ISSUE TITLE
Empty, unreferenced arrays are not being serialized

### ISSUE THREAD

**Issue by heaths** [xoofx/Tomlyn#98]
When serializing a dictionary, any keys that are empty arrays but unreferenced are not being serialized. Consider the following TOML:

```toml
[features]
default = ["foo"]
foo = []
bar = []
```

A fairly common `Cargo.toml` manifest with default and non-default features. Deserializing this produces the expected ordered dictionary with array members for all three of default, foo, and bar. Serializing the resulting object only produces:

```toml
[features]
default = ["foo"]
foo = []
```

Notice that bar is missing.

This is causing jborean93/PSToml#10, which we currently use in the Azure SDK for Rust pipelines. If there is a way to work around this for now, that would be great; however, looking through your documentation nothing pops out at me.

**Comment by heaths** [comment]
With some additional testing of tomlyn directly @hallipr found it's actually just dropping the last entry:

```csharp
var model = new TomlTable();
model.Add("something", "string value");
model.Add("array1", new TomlArray() { "hello" });
model.Add("array2", new TomlArray() { });
model.Add("array3", new TomlArray() { });
Console.WriteLine(Toml.FromModel(model));
```

```toml
something = "string value"
array1 = ["hello"]
array2 = []
```

There's no key named "string value" and both `array2` and `array3` are empty, but only `array2` is serialized.
